### PR TITLE
fix #149 Non string keys

### LINKED ISSUE #149: Non string keys are not excluded from rest object
```
const source = { 1: 'one', 2: 'two' };
const { 1: _, ...rest } = source;
console.assert(!(1 in rest));
```

this test is failed when compiled with buble

```
function objectWithoutProperties (obj, exclude) { var target = {}; for (var k in obj) if (Object.prototype.hasOwnProperty.call(obj, k) && exclude.indexOf(k) === -1) target[k] = obj[k]; return target; }
var source = { 1: 'one', 2: 'two' };
var _ = source[1];
var rest$1 = objectWithoutProperties( source, [1] );
var rest = rest$1;
console.assert(!(1 in rest));
```

it uses indexOf which does strict equality so non-string keys are not ommited

### PR DESCRIPTION
**Pull request by exe-dealer**

### CODE REVIEW

**Comment by adrianheine** [comment]
That looks very good. Are you interested in adding some tests? Otherwise I'd merge this as it is and tests myself.

**Comment by adrianheine** [comment]
Thanks! I'd like to have the commits squashed into one and with a commit message that's a somewhat complete phrase and starts with an upper-case letter. I also need to set up travis integration again after moving the repo to the new bublejs organization. You're code changes are good to merge from my point of view, though :)

**Comment by exe-dealer** [comment]
what about to replace String(expr) to ""+expr ? Last code is uglier but its protected from String redeclaration

**Comment by adrianheine** [comment]
I think I would prefer `String`, since it is prettier and performs the correct operation (`toString`, not `valueOf`). 

```js
class X {
  valueOf() { return "valueOf" }
  toString() { return "toString" }
}

console.log(
  { [new X()]: "new X()" },
  (new X()) + "",
  String(new X()),
  { valueOf: "valueOf", toString: "toString" }[new X()]
)
```

**Comment by adrianheine** [comment]
Ok, I merged this. Thanks for your patience!

**Pull request merged**
